spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: r1
            uri: http://localhost:8081/
            predicates:
              - Path=/customers/**
          - id: r2
            uri: http://localhost:8082/
            predicates:
              - Path=/claims/**
          - id : r3
            uri : http://localhost:8083/
            predicates :
              - Path=/notifications/**
      globals:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
application:
  name: gateway-service

server:
  port: 8888
